version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=spark_hub
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data-capstone:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: docker.io/redis
    restart: always
    volumes:
      - redis-data:/data
    command: redis-server --save 60 1
    networks:
      - backend

  server:
    image: ${IMAGE}/server:latest # localhost/capstone-server
    depends_on:
      - redis
      - db
    environment:
      - DB_CONN_STRING=postgres://postgres:password@db:5432/spark_hub
      - REDIS_CONN=redis://redis:6379
      - UPLOAD_PATH=/uploads
    volumes:
      - img-upload:/uploads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.capstoneapi.rule=Host(`api.capstone.apps.jmidd.dev`)"
      - "traefik.http.routers.capstoneapi.tls=true"
      - "traefik.http.routers.capstoneapi.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.capstoneapi.tls.domains[0].main=api.capstone.apps.jmidd.dev"
      - "traefik.docker.network=external"
    networks:
      backend:
      frontend:

  frontend:
    image: ${IMAGE}/frontend:latest #  localhost/capstone-frontend
    depends_on:
      - server
    volumes:
      - img-upload:/usr/share/nginx/html/images/uploads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.capstoneapp.rule=Host(`capstone.apps.jmidd.dev`)"
      - "traefik.http.routers.capstoneapp.tls=true"
      - "traefik.http.routers.capstoneapp.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.capstoneapp.tls.domains[0].main=capstone.apps.jmidd.dev"
      - "traefik.docker.network=external"
    networks:
      - frontend
    
volumes:
  db-data-capstone:
  redis-data:
  img-upload:

networks:
    frontend:
        name: external
        external: true
    backend:
