version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=spark_hub
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data-capstone:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: docker.io/redis
    restart: always
    volumes:
      - redis-data:/data
    command: redis-server --save 60 1 --loglevel verbose
    networks:
      - backend

  server:
    image: ${IMAGE}/server:${COMMIT_SLUG}
    depends_on:
      - redis
      - db
    ports:
      - "3001"
    environment:
      - DB_CONNECTION_STRING=postgres://postgres:password@db:5432/spark_hub
      - REDIS_CONN_STRING=redis://redis:6379
    labels:
      - "traefik.http.routers.capstoneapistaging.rule=Host(`capstoneapi.staging.apps.techpulse.us`)"
    networks:
      - backend
      - frontend

  frontend:
    image: ${IMAGE}/frontend:${COMMIT_SLUG}
    ports:
      - "3000"
    depends_on:
      - server
    environment:
      - SERVER_STRING=http://capstoneapi.staging.apps.techpulse.us
    labels:
      - "traefik.http.routers.capstonestaging.rule=Host(`capstone.staging.apps.techpulse.us`)"
    networks:
      - frontend

    
volumes:
  db-data-capstone:
  redis-data:

networks:
    frontend:
        name: traefik-network
        external: true
    backend:
