name: Docker Image CI

on:
  push:
    branches: [ "docker-deploy-test" ]
  pull_request:
    branches: [ "docker-deploy-test" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file server/Dockerfile --tag kyle-koch/capstone:test-$(date +%s)
